### ISSUE TITLE
Unable to upload Mapping file

### ISSUE THREAD

**Issue by shubhamMonga777** [DataDog/dd-sdk-android-gradle-plugin#124]
**No matching variant of com.datadoghq:dd-sdk-android-gradle-plugin:1.3.0 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.3.3' but:
          - Variant 'apiElements' capability com.datadoghq:dd-sdk-android-gradle-plugin:1.3.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8**

**Comment by xgouchet** [comment]
Hi @shubhamMonga777, can you please give us more information about this issue: 
- your gradle configuration
- the steps to reproduce this issue

**Comment by shubhamMonga777** [comment]
**Issue resolved.**

My System java version was different from studio jdk version, after updating to **JDK11** on system ,Its working now
Thanks
