### ISSUE TITLE
Unable to upload mapping file using Dexguard

### ISSUE THREAD

**Issue by gustavobonaldi** [DataDog/dd-sdk-android-gradle-plugin#132]
**Describe what happened**

Dexguard expects its inputs to be unobfuscated, disabling minify.
And with minify disabled, uploadMapping tasks are not created.

**Describe what you expected:**

Would it be possible to remove the minify check?

**Additional context**

- Dexguard docs:
![image](https://user-images.githubusercontent.com/39656251/211686215-b3a2fb8f-93b5-4d6c-adaf-c3e2c6f62684.png)
![image](https://user-images.githubusercontent.com/39656251/211686590-ab67eea0-2abb-4eab-b4c6-34c5c6d44313.png)

**Comment by xgouchet** [comment]
Hi @gustavobonaldi, and thanks for reporting this limitation.
We'll take a look to ensure our uploader works with dexguard.

**Comment by gustavobonaldi** [comment]
Thank you, @xgouchet!
