### ISSUE TITLE
serviceName is not correctly set

### ISSUE THREAD

**Issue by akinzalowevidation** [DataDog/dd-sdk-android-gradle-plugin#147]
**Describe what happened**
I am setting `serviceName` in `build.gradle` but not seeing the service name I set used in the `datadog-ci` command.

build.gradle:
```
datadog {
  serviceName: "my-service"
}
```
```
$ /Users/***/Desktop/Engineering/packages/native/node_modules/.bin/datadog-ci react-native upload --platform android --service com.***.android.development --bundle /Users/***/Desktop/Engineering/***/packages/native/android/app/build/generated/assets/react/development/release/index.android.bundle --sourcemap /Users/***/Desktop/Engineering/packages/native/android/app/build/generated/sourcemaps/react/development/release/index.android.bundle.map --release-version *** --build-version ***
Starting upload. 
Upload of /Users/***/Desktop/Engineering/packages/native/android/app/build/generated/sourcemaps/react/development/release/index.android.bundle.map for bundle /Users/***/Desktop/Engineering/packages/native/android/app/build/generated/assets/react/development/release/index.android.bundle on platform android with project path /Users/allenkinzalow/Desktop/Engineering/packages/native
version: *** build: *** service: com.***.android.development
```

**Steps to reproduce the issue:**
1. Set `serviceName` under `datadog` configuration in `build.gradle`.
2. Run a release variant build
3. Observe `--service` not set to `serviceName`.

**Describe what you expected:**

**Additional context**
 - Android Build Tools version: 31
 - Gradle version: 7.0.4
 - OS version: MacOS 13.2
 - Plugin version: 1.7.0

**Comment by 0xnm** [comment]
Hello @akinzalowevidation! Source maps upload for our React Native SDK is not using `dd-sdk-android-gradle-plugin`, so anything you have in the `datadog` extension has no effect. Please open this issue in the React Native SDK repository [issue tracker](https://github.com/DataDog/dd-sdk-reactnative/issues).
