### ISSUE TITLE
Provide example for variants configuration with Kotlin DSL

### ISSUE THREAD

**Issue by thomasflad** [DataDog/dd-sdk-android-gradle-plugin#154]
Hi DataDog Team,

I'm struggling with setting up a configuration per variant in a Kotlin Script Gradle file. Can you provide an example how it should look like? 

```
datadog {
    site = "US" // Variants with no configurations will use this as default
    variants {
        fr {
            site = "EU"
            mappingFilePath = "path/to/fr/mapping.txt"
        }
    }
}
```

**Comment by 0xnm** [comment]
Hello @thomasflad! Thanks for reporting this issue, indeed `variants` property configuration is not compatible with Kotlin DSL.

When using Groovy, it is capable to doing some conversions thanks to the meta-programming capabilites.

Kotlin DSL on another hand is statically typed, so some things should be more explicit. For the moment, the example you posted will look like following in Kotlin DSL:

```kotlin
datadog {
    site = "US"
    withGroovyBuilder {
        "variants" {
            "create"("fr") {
                setProperty("site", "EU")
                setProperty("mappingFilePath", "path/to/fr/mapping.txt")
            }
        }
    }
}
```

Here I used [withGroovyBuilder](https://docs.gradle.org/current/userguide/kotlin_dsl.html#the_kotlin_dsl_groovy_builder) which may not look nice, but at least does the job. Alternatively you can write configuration in Groovy and apply it using [dynamic-groovy-plugin](https://docs.gradle.org/current/userguide/kotlin_dsl.html#using_a_groovy_script).

In the meantime we will do the necessary changes to be compatible with Kotlin DSL for `variants` property and will try to ship the fix soon.
