### ISSUE TITLE
Different Variants in datadog kotlin gradle cannot be resolved

### ISSUE THREAD

**Issue by KamilPieta** [DataDog/dd-sdk-android-gradle-plugin#195]
I follow your guidelines [Plugin Configuration Options](https://docs.datadoghq.com/real_user_monitoring/error_tracking/android/?tab=eu#plugin-configuration-options)  and cannot change serviceName field depending on build variant. I don't know why this example is written in groovy and in your sample is commented out https://github.com/DataDog/dd-sdk-android-gradle-plugin/blob/develop/samples/variants/build.gradle

  ```
  datadog {
        site = "EU1"
        mappingFileTrimIndents = true
        create("Flavour1") {
            serviceName = "AppServiceOne"
        }
        create("Flavour2") {
            serviceName = "AppServiceTwo"
        }
    }
```

**Comment by 0xnm** [comment]
Hello @KamilPieta! If you are using Kotlin Build Script, can you check if the following answer https://github.com/DataDog/dd-sdk-android-gradle-plugin/issues/154#issuecomment-1463730497 solves your issue?

**Comment by KamilPieta** [comment]
That helped, thanks!
