### ISSUE TITLE
Where to put this on multi module project?

### ISSUE THREAD

**Issue by mpaduchh** [DataDog/dd-sdk-android-gradle-plugin#22]
Hi Guys,
This is not really a bug, just a question.. I have a multi module project and I tried putting this on main app module and also on every module but I always get the

"The dd-android-gradle-plugin has been applied on a non android application project" warning.

Is this ok?

**Comment by 0xnm** [comment]
Hi @mpaduchh,

Thanks for contacting us. Plugin is supposed to work with application module only, so it should be added only once in your setup. Let us know if you have more questions or experience other issues with plugin installation.

**Comment by pvegh** [comment]
Please update the samples, they contain commented code and it's not clear where to add things exactly

**Comment by xgouchet** [comment]
Hi, @pvegh, as mentionned in our [documentation](https://docs.datadoghq.com/real_user_monitoring/error_tracking/android/?tab=us), you need to add the plugin to your application's `build.gradle` or `build.gradle.kts` file: 

```
// In your app's build.gradle script
plugins {
    id("com.datadoghq.dd-sdk-android-gradle-plugin") version "x.y.z"
}
```

We have a project to indeed make our samples project more understandable, which should be done in the next few months.
