### ISSUE TITLE
Release 1.14.0 isn't on maven central. 

### ISSUE THREAD

**Issue by yogurtearl** [DataDog/dd-sdk-android-gradle-plugin#272]
Release `1.14.0` isn't on maven central: 
https://repo.maven.apache.org/maven2/com/datadoghq/dd-sdk-android-gradle-plugin/

Guessing it is just "coming soon" ? if so, feel free to close this. 
 
but filing in case it was an actual problem that caused it to not be published there.

**Comment by 0xnm** [comment]
Hello @yogurtearl! It should be available now on Maven Central, thanks for flagging that.
