### ISSUE TITLE
UploadMapping* Tasks not available

### ISSUE THREAD

**Issue by ConnorJBishop** [DataDog/dd-sdk-android-gradle-plugin#273]
**Describe what happened**
Adding the plugin to build.gradle script in a kotlin project does not provide any `uploadMapping*` tasks

**Steps to reproduce the issue:**

1. Create a minimal Kotlin application in Android Studio
2. Add ` id("com.datadoghq.dd-sdk-android-gradle-plugin") version "1.14.0"` in the plugins block in the `app/build.gradle.kts` file
3. Sync gradle file changes (`Task :prepareKotlinBuildScriptModel`)
4. Build project
5. Run `gradlew uploadMappingDebug`
6. Observe `Task 'uploadMappingDebug' not found in root project 'My Application' and its subprojects.`

**Describe what you expected:**
`uploadMappingDebug` task to be available

**Additional context**
 - Gradle version: 8.0
 - Plugin version: 1.14.0

**Comment by 0xnm** [comment]
Hello @ConnorJBishop!

Upload tasks will only be created for the particular application variant if it has `isMinifyEnabled = true` (or `nonDefaultObfuscation = true` in `datadog` extension) or if it has NDK files to build.

Can you please share your build configuration?

**Comment by ConnorJBishop** [comment]
@0xnm thanks for your reply. It was indeed related to my build config, I can see the tasks now :)
