### ISSUE TITLE
Gradle plugin doesn't work with Gradle Configuration Cache (7.x)

### ISSUE THREAD

**Issue by pvegh** [DataDog/dd-sdk-android-gradle-plugin#39]
There is a new feature in Gradle, the configuration cache. The goal is not to execute the config step every time, it can be cached if the plugins support this.
We want to enable this feature, it would save us time, and especially these hot summer days, it's a double win for laptop users (hot machine->slowew build->even hotter->even slower).

The build fails with the current version of the dd-gradle-plugin when we enable this new Gradle feature by adding **org.gradle.unsafe.configuration-cache=true** to **gradle.properties**

Datadog gradle plugin 1.0.1
Gradle 7.1

Documentation: https://docs.gradle.org/current/userguide/configuration_cache.html

1: Task failed with an exception.
-----------
```
* What went wrong:
Configuration cache state could not be cached: field 'actions' from type 'org.gradle.api.DefaultTask': error writing value of type 'java.util.ArrayList'
> Configuration cache state could not be cached: field 'action' from type 'org.gradle.api.internal.AbstractTask$TaskActionWrapper': error writing value of type 'com.datadog.gradle.plugin.DdAndroidGradlePlugin$configureVariantForSdkCheck$1'
   > Configuration cache state could not be cached: field '$variant' from type 'com.datadog.gradle.plugin.DdAndroidGradlePlugin$configureVariantForSdkCheck$1': error writing value of type 'com.android.build.gradle.internal.api.ApplicationVariantImpl'
   > Configuration cache state could not be cached: field 'unitTestVariant' from type 'com.android.build.gradle.internal.api.ApplicationVariantImpl': error writing value of type 'com.android.build.gradle.internal.api.UnitTestVariantImpl'
   > Configuration cache state could not be cached: field 'variantData' from type 'com.android.build.gradle.internal.api.UnitTestVariantImpl': error writing value of type 'com.android.build.gradle.internal.variant.TestVariantData'
   > Configuration cache state could not be cached: field 'testedVariantData' from type 'com.android.build.gradle.internal.variant.TestVariantData': error writing value of type 'com.android.build.gradle.internal.variant.ApplicationVariantData'
   > Configuration cache state could not be cached: field 'globalScope' from type 'com.android.build.gradle.internal.variant.ApplicationVariantData': error writing value of type 'com.android.build.gradle.internal.scope.GlobalScope'
   > Configuration cache state could not be cached: field 'extension' from type 'com.android.build.gradle.internal.scope.GlobalScope': error writing value of type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension'
   > Configuration cache state could not be cached: field 'publicExtensionImpl' from type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension': error writing value of type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated'
   > Configuration cache state could not be cached: field 'buildTypes' from type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated': error writing value of type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer'
   > Configuration cache state could not be cached: field 'eventRegister' from type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer': error writing value of type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister'
   > Configuration cache state could not be cached: field 'addActions' from type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister': error writing value of type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions'
   > Configuration cache state could not be cached: field 'actions' from type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions': error writing value of type '[Lorg.gradle.api.Action;'
   > Configuration cache state could not be cached: field 'delegate' from type 'org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction': error writing value of type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1'
   > Configuration cache state could not be cached: field 'val$action' from type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1': error writing value of type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager$3'
   > Configuration cache state could not be cached: field '$tmp0' from type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager$3': error writing value of type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager'
   > Configuration cache state could not be cached: field 'sourceSetManager' from type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager': error writing value of type 'com.android.build.gradle.internal.dependency.SourceSetManager'
   > Configuration cache state could not be cached: field 'sourceSetsContainer' from type 'com.android.build.gradle.internal.dependency.SourceSetManager': error writing value of type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer'
   > Configuration cache state could not be cached: field 'eventRegister' from type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer': error writing value of type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister'
   > Configuration cache state could not be cached: field 'addActions' from type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister': error writing value of type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions'
   > Configuration cache state could not be cached: field 'actions' from type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions': error writing value of type '[Lorg.gradle.api.Action;'
   > Configuration cache state could not be cached: field 'delegate' from type 'org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction': error writing value of type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1'
   > Configuration cache state could not be cached: field 'val$action' from type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1': error writing value of type 'org.jetbrains.kotlin.gradle.plugin.mpp.SyncKotlinAndAndroidSourceSetsKt$syncKotlinAndAndroidSourceSets$1'
   > Configuration cache state could not be cached: field '$target' from type 'org.jetbrains.kotlin.gradle.plugin.mpp.SyncKotlinAndAndroidSourceSetsKt$syncKotlinAndAndroidSourceSets$1': error writing value of type 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget'
   > Configuration cache state could not be cached: field 'kotlinComponents$delegate' from type 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget': error writing value of type 'kotlin.SynchronizedLazyImpl'
   > KotlinJvmAndroidCompilation with name 'main' not found.
```

**Comment by 0xnm** [comment]
Hello @pvegh. Can you specify the exact versions of Gradle and Android Gradle plugin you are using? I'm able to get an error with `--configuration-cache` flag, but it is different from yours.

**Comment by pvegh** [comment]
AGP 7.0.0-beta04
Gradle 7.1

**Comment by 0xnm** [comment]
Hello @pvegh. This should be fixed in the PR above, it will be shipped with a next release of plugin. The important point is that plugin does dependencies check and API for that which is compatible with configuration cache is not yet available in Gradle. However, if you do `checkProjectDependencies = none` in the extension configuration, it will skip dependencies check part and plugin will be compatible with configuration cache feature. Please let us know if you have any other issues.

**Comment by 0xnm** [comment]
Hello @pvegh. We've published new version [1.1.0](https://search.maven.org/artifact/com.datadoghq/dd-sdk-android-gradle-plugin/1.1.0/aar), so please try it and let us know if it works for you.

**Comment by pvegh** [comment]
checkProjectDependencies = "none"
makes the project build with config cache, thanks. 

1.1.0 with the fix above leads to a new error/stacktrace:
Gradle 7.1.1
AGP 7.0.0 (now stable, maybe they changed something)

* What went wrong:
Configuration cache state could not be cached: field 'actions' from type 'org.gradle.api.DefaultTask': error writing value of type 'java.util.ArrayList'
> Configuration cache state could not be cached: field 'action' from type 'org.gradle.api.internal.AbstractTask$TaskActionWrapper': error writing value of type 'com.datadog.gradle.plugin.DdAndroidGradlePlugin$configureVariantForSdkCheck$1'
   > Configuration cache state could not be cached: field '$variant' from type 'com.datadog.gradle.plugin.DdAndroidGradlePlugin$configureVariantForSdkCheck$1': error writing value of type 'com.android.build.gradle.internal.api.ApplicationVariantImpl'
      > Configuration cache state could not be cached: field 'unitTestVariant' from type 'com.android.build.gradle.internal.api.ApplicationVariantImpl': error writing value of type 'com.android.build.gradle.internal.api.UnitTestVariantImpl'
         > Configuration cache state could not be cached: field 'variantData' from type 'com.android.build.gradle.internal.api.UnitTestVariantImpl': error writing value of type 'com.android.build.gradle.internal.variant.TestVariantData'
            > Configuration cache state could not be cached: field 'testedVariantData' from type 'com.android.build.gradle.internal.variant.TestVariantData': error writing value of type 'com.android.build.gradle.internal.variant.ApplicationVariantData'
               > Configuration cache state could not be cached: field 'globalScope' from type 'com.android.build.gradle.internal.variant.ApplicationVariantData': error writing value of type 'com.android.build.gradle.internal.scope.GlobalScope'
                  > Configuration cache state could not be cached: field 'dslServices' from type 'com.android.build.gradle.internal.scope.GlobalScope': error writing value of type 'com.android.build.gradle.internal.services.DslServicesImpl'
                     > Configuration cache state could not be cached: field 'projectServices' from type 'com.android.build.gradle.internal.services.DslServicesImpl': error writing value of type 'com.android.build.gradle.internal.services.ProjectServices'
                        > Configuration cache state could not be cached: field 'deprecationReporter' from type 'com.android.build.gradle.internal.services.ProjectServices': error writing value of type 'com.android.build.gradle.internal.errors.DeprecationReporterImpl'
                           > Configuration cache state could not be cached: field 'issueReporter' from type 'com.android.build.gradle.internal.errors.DeprecationReporterImpl': error writing value of type 'com.android.build.gradle.internal.errors.SyncIssueReporterImpl'
                              > Configuration cache state could not be cached: field 'messageReceiverImpl' from type 'com.android.build.gradle.internal.errors.SyncIssueReporterImpl': error writing value of type 'com.android.build.gradle.internal.errors.MessageReceiverImpl'
                                 > Configuration cache state could not be cached: field 'mGson' from type 'com.android.build.gradle.internal.errors.MessageReceiverImpl': error writing value of type 'com.google.gson.Gson'
                                    > Configuration cache state could not be cached: field 'constructorConstructor' from type 'com.google.gson.Gson': error writing value of type 'com.google.gson.internal.ConstructorConstructor'
                                       > Configuration cache state could not be cached: field 'accessor' from type 'com.google.gson.internal.ConstructorConstructor': error writing value of type 'com.google.gson.internal.reflect.UnsafeReflectionAccessor'
                                          > Configuration cache state could not be cached: field 'overrideField' from type 'com.google.gson.internal.reflect.UnsafeReflectionAccessor': error writing value of type 'java.lang.reflect.Field'
                                             > Configuration cache state could not be cached: field 'overrideFieldAccessor' from type 'java.lang.reflect.Field': error writing value of type 'jdk.internal.reflect.UnsafeBooleanFieldAccessorImpl'
                                                > Unable to make field protected final java.lang.reflect.Field jdk.internal.reflect.UnsafeFieldAccessorImpl.field accessible: module java.base does not "opens jdk.internal.reflect" to unnamed module @7ca85d5e

**Comment by 0xnm** [comment]
@pvegh That is strange indeed, because by looking on the stacktrace it references anonymous lambda here https://github.com/DataDog/dd-sdk-android-gradle-plugin/blob/5e7f5ebfc258f0c74d1345f54821df7a0a0529be/dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt#L149 which shouldn't be created if `checkProjectDependencies = none`. Did you try to [clean configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:usage:invalidate) before running your test?

**Comment by pvegh** [comment]
Oh if I add the line then it works. I understood it like that was only the workaround for 1.0 until 1.1 is released.
I think the plugin should work out of the box even with config cache enabled, without that additional opt-out line.
Maybe make it opt-in? Seems like it isn't useful for some/many/most of us anyway? Not sure, but maybe something to consider.
