### ISSUE TITLE
Issue while adding DD-SDK to my project

### ISSUE THREAD

**Issue by victorlsn** [DataDog/dd-sdk-android-gradle-plugin#54]
Thanks in advance for your help.

I'm trying to add DD RUM to my company's Android project, but I keep getting the following errors:

org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'dd-sdk-android-gradle-plugin'] was not found in any of the following sources:

The relevant part of my build.gradle is like this:
```
buildscript {
    ext.kotlin_version = '1.5.31'
    ext.clay_odata_version = '0.1.12'
    ext.compose_version = '1.1.0-beta02'
    ext.sonarqube_version = "3.2.0"

    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.0-alpha02'
        // the latest version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        // google analytics
        classpath 'com.google.gms:google-services:4.3.8'
        // gradle plugin for AppCenter
        classpath 'gradle.plugin.com.betomorrow.gradle:appcenter-plugin:1.3.0'
        // Google Protocol Buffers
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.12'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath "io.realm:realm-gradle-plugin:10.7.0"
        // retrolambda
        classpath 'me.tatarka:gradle-retrolambda:3.7.0'
        // Kotlin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // SonarQube
        classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:$sonarqube_version"
        // KTLint
        classpath("org.jmailen.gradle:kotlinter-gradle:2.4.1")
        // Sentry
        classpath 'io.sentry:sentry-android-gradle-plugin:1.7.36'
        classpath 'com.android.tools.build:gradle:7.1.0-alpha02'
        classpath("com.datadoghq:dd-sdk-android-gradle-plugin:x.x.x")
    }
}

plugins {
    id "org.sonarqube" version "$sonarqube_version"
    id "org.jmailen.kotlinter" version "2.4.1"
    id("dd-sdk-android-gradle-plugin")
}
```

Using:
Android Studio Bumblebee 2021.1.1 Canary 1
Android Build Tools 32.0.0-rc1
Gradle 7.0

**Comment by 0xnm** [comment]
Hello @victorlsn. Which plugin version are you using? The latest one is `1.1.0`(you can check it here https://mvnrepository.com/artifact/com.datadoghq/dd-sdk-android-gradle-plugin). Also do you apply it in the application module?

**Comment by victorlsn** [comment]
Hello @0xnm. Thanks for your answer.
The point is (was) that gradle would not even sync when adding these on the project-level build.gradle:        classpath("com.datadoghq:dd-sdk-android-gradle-plugin:x.x.x") to dependencies
id("dd-sdk-android-gradle-plugin") to  plugins

**Comment by victorlsn** [comment]
I just get this error:
Build file '/Users/victor/Documents/Projects/Android/app_android_v3/build.gradle' line: 46

Plugin [id: 'dd-sdk-android-gradle-plugin'] was not found in any of the following sources:

**Comment by 0xnm** [comment]
@victorlsn Our plugin is not on Gradle Plugin portal yet (only Maven Central), so since `plugin { }` block is working only with Gradle Plugin portal by default unlike `apply plugin`, you can add the following to your `settings.gradle` file:

```gradle
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "dd-sdk-android-gradle-plugin") {
                useModule("com.datadoghq:dd-sdk-android-gradle-plugin:${requested.version}")
            }
        }
    }
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
```

Also make sure to specify the version in the plugins block.

**Comment by victorlsn** [comment]
Thanks a lot @0xnm, this worked perfectly.!

**Comment by boldijar** [comment]
so @0xnm is there a way to import the android plugin without the settings.gradle hack above?

**Comment by 0xnm** [comment]
Hi @boldijar. Yes, we now have it published on [Gradle Plugin portal](https://plugins.gradle.org/plugin/com.datadoghq.dd-sdk-android-gradle-plugin), check instructions there.
