### ISSUE TITLE
Execution failed for task 'checkSdkDeps'

### ISSUE THREAD

**Issue by batadamnjanovic** [DataDog/dd-sdk-android-gradle-plugin#62]
Hi all. 

We have a problem with applying Datadog Gradle plugin `com.datadoghq:dd-sdk-android-gradle-plugin:1.2.0`.

When the plugin is applied in the app's build.gradle script with `id("com.datadoghq.dd-sdk-android-gradle-plugin"), we get the following error when we run a build(assemble task).

We have two flavors: production and staging.
Both flavors have debug and release variants.
We have the app module that include several other modules as dependencies.

**Additional context**
 - Android Build Tools version: 4.1.3
 - Gradle version: 7.3.1
 - OS version: Mac OS Big Sur 11.4
 - Plugin version: 1.2.0

Stacktrace: 
`Execution failed for task ':app:checkSdkDepsStagingDebug'.
> Error while evaluating property 'configuration' of task ':app:checkSdkDepsStagingDebug'
   > Could not resolve all files for configuration ':app:stagingDebugCompileClasspath'.
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:
          - Configuration ':features:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:splash:
          - Configuration ':features:splash:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:splash:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:splash:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:splash:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:auth:
          - Configuration ':features:auth:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:auth:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:auth:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:auth:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:scanner:
          - Configuration ':features:scanner:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:scanner:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:scanner:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:scanner:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:home:
          - Configuration ':features:home:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:home:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:home:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:home:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:payment:
          - Configuration ':features:payment:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:payment:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:payment:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:payment:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:editor:
          - Configuration ':features:editor:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:editor:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:editor:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:editor:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :features:widget:
          - Configuration ':features:widget:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:widget:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:widget:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':features:widget:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :common:core:
          - Configuration ':common:core:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :common:workflow:
          - Configuration ':common:workflow:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:workflow:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:workflow:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:workflow:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :common:core-ui:
          - Configuration ':common:core-ui:stagingDebugApiElements' variant android-databinding-class-log declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-databinding-class-log' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core-ui:stagingDebugApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core-ui:stagingDebugApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it
          - Configuration ':common:core-ui:stagingDebugApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'configuration' with value 'staging', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'stagingDebug' but the consumer didn't ask for it`

**Comment by batadamnjanovic** [comment]
Yes, of course. But it is not really simple to read :)
https://gist.github.com/batadamnjanovic/959f7192e26aa1dae75be94bfc26f523

**Comment by 0xnm** [comment]
Hello @batadamnjanovic! We've released version `1.2.1`, this issue should be solved there.

**Comment by batadamnjanovic** [comment]
Hi @0xnm, this is what we get now
```
What went wrong:
Execution failed for task ':app:checkSdkDepsStagingDebug'.
> Following application variant doesn't have Datadog SDK included: stagingDebug
```

Thanks!

**Comment by 0xnm** [comment]
Hi @batadamnjanovic. Does `stagingDebug` variant have a dependency on our SDK? If no, then you can disable check for this variant by doing:

```
datadog {
    variants {
        stagingDebug {
            checkProjectDependencies = "none"
        }
    }
}
```

If `stagingDebug` has a dependency on our SDK, please open another issue with the relevant information.
