### ISSUE TITLE
Please state clearly that deobfuscated stack traces are only available if you use RUM

### ISSUE THREAD

**Issue by nordfalk** [DataDog/dd-sdk-android-gradle-plugin#78]
I have spent some time trying to figure out why stack traces are not de-obfuscated, even through my mapping file seemd to be uploaded. 

There was no place on the website I could see that it **was** uploaded, and the gradle task was silent, it didnt tell that it was actually uploaded successfully. So, I resorted to to sniff network traffic to check that the gradle plugin actually uploaded **something**..... it was, but but still no deobfuscation. 

I decided for next step that I'll have to try to download gradle plugin source to debug the plugin.

Then, fortunately, I randomly found this side comment:
https://github.com/DataDog/dd-sdk-android-gradle-plugin/issues/65#issuecomment-998911790

... and only then I realized that it was actually working, but only for RUM and not for the logs where I was looking.

I shouldn't have to dig so deep in your bug report comments to find out that deobfuscation simply isnt supported for logs :-)

Instead, the current state and limitations - that deobfuscated stack traces are only available if you use RUM - should be stated in
https://github.com/DataDog/dd-sdk-android-gradle-plugin#troubleshooting

**Comment by xgouchet** [comment]
Hi @nordfalk, Thanks a lot for reporting this. I'm deeply sorry you lost so much time on this issue and apologise for this bad experience. Indeed, so far only stack traces in RUM Errors are deobfuscated. We'll update our documentation to ensure that this is clearer.

**Comment by nordfalk** [comment]
No problem! 
We are all humans - thanks for making a great product :-)
