### ISSUE TITLE
Transitive dependency causes `checkSdkDeps` task to fail

### ISSUE THREAD

**Issue by mati1** [DataDog/dd-sdk-android-gradle-plugin#85]
**Describe what happened**
If the DD SDK is included but not in the `app` module, this causes the check to fail.

**Steps to reproduce the issue:**
1. Create android App 
2. Add an android library
3. Add android library as a dependency
3. Apply DD Plugin to app
4. Add DD Sdk dependency to the library
5. Run `checkSdkDeps` and it will fail

**Describe what you expected:**
`checkSdkDeps` shouldn't fail

**Additional context**
 - Android Build Tools version: 31
 - Gradle version: 7.4.1
 - OS version: Mac OS X 12.3.1 aarch6
 - Plugin version: 1.3.0
 - Proguard configuration: None
 - Other Gradle Plugins: None

**Comment by 0xnm** [comment]
Hello @mati1. Thanks for reporting the issue, we will take a look. In the meantime you can disable this check by setting `checkProjectDependencies` to `none` in the plugin extension.

**Comment by orafaaraujo** [comment]
Hello, 

I'm facing the same and I have a question, should we add the plugin in the `app/build.gradle` or in the library module that it's holding Datadog dependencies and implementations?

Thank you

**Comment by 0xnm** [comment]
Hello @orafaaraujo! Plugin should be applied to the application module. Can you please post the stacktrace of the error you have?

**Comment by orafaaraujo** [comment]
Hey, @0xnm 

Thank you for your quick reply.

Here's the message

```
> Task :app:checkSdkDepsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkSdkDepsDebug'.
> Following application variant doesn't have Datadog SDK included: debug
```

If I add the dependency in `app/build.gradle` I can build correctly. Or using the set mentioned above, which is what I'm doing.

**Comment by 0xnm** [comment]
We disabled this check by default for now.
