### ISSUE TITLE
Enable de-obfuscation for DataDog Logs

### ISSUE THREAD

**Issue by miroslav404** [DataDog/dd-sdk-android-gradle-plugin#95]
**Is your feature request related to a problem? Please describe.**
It would be really useful to see de-obfuscated logs after mapping.txt is uploaded, do you have plan to enable de-obfuscation also for DataDog logs.

**Comment by Maxwell6635** [comment]
Would it better de-obfuscated for DataDog RUM for any tracking view , I believe the class name it will become obfuscated if enable proguard.

**Comment by xgouchet** [comment]
Hi @miroslav404 , and thanks for opening this feature request. So far we only support deobfuscating stacktraces from Errors reported through RUM, and deobfuscating logs is not on our immediate roadmap but we'll keep you updated if we eventually do it.

**Comment by nordfalk** [comment]
We at Visma Dinero would also really like deobfuscation to work in the logs.

Its essential for crash reporting to be able to be able to see the stack trace. Our 'workaround' is to use Crashlytics....

**Comment by 0xnm** [comment]
Android stacktrace de-obfuscation is now supported for errors in Logs.

If your application doesn't have flavors, you can continue using the current Datadog SDK version in your application.

If your application has flavors, please make sure to upgrade Datadog SDK to the freshly release version [1.14.0-beta2](https://search.maven.org/artifact/com.datadoghq/dd-sdk-android/1.14.0-beta2/aar) and correctly specify `variant` property of `Credentials` object during the SDK configuration (should be the same value as `BuildConfig.FLAVOR` by default).

**Comment by nordfalk** [comment]
It works - thanks, I'm very happy :-)
